version: "3"
services:
  csharp:
    container_name: csharp
    image: dennismitchellx/csharp:1.0.0
    build: ./c#  
  golang:
    container_name: golang
    image: dennismitchellx/golang:1.0.0
    build: ./golang
  nodejs:
    container_name: nodejs
    image: dennismitchellx/nodejs:1.0.0
    build: ./nodejs
  python:
    container_name: python
    image: dennismitchellx/python:1.0.0
    build: ./python
